# Generated by Django 3.0.8 on 2023-11-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20231121_2008'),
        ('dashboard', '0002_auto_20231122_1507'),
    ]

    operations = [
    ]
