# Generated by Django 4.1.9 on 2023-11-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20231121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridlayout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
