# Generated by Django 4.1.9 on 2024-01-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_gridlayout_id'),
        ('dashboard', '0003_merge_20231127_1044'),
    ]

    operations = [
    ]
