# Generated by Django 3.0.8 on 2023-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('cypher', models.TextField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('cypher', models.TextField(max_length=9999)),
            ],
        ),
    ]
