# Generated by Django 3.0.8 on 2023-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicypher',
            name='cypher_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cypher',
            name='cypher_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apicypher',
            name='cypher',
            field=models.TextField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='cypher',
            name='cypher',
            field=models.TextField(default='', max_length=9999),
        ),
    ]
