# Generated by Django 3.0.8 on 2023-09-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230913_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicypher',
            name='index',
        ),
        migrations.RemoveField(
            model_name='cypher',
            name='index',
        ),
        migrations.AddField(
            model_name='cypher',
            name='function_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apicypher',
            name='cypher_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cypher',
            name='cypher_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
