# Generated by Django 4.1.9 on 2023-09-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apicypher_id_alter_cypher_id'),
        ('api', '0003_auto_20230920_0546'),
    ]

    operations = [
    ]
