# Generated by Django 4.1.9 on 2024-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_evidence_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='uploadedFile',
            field=models.FileField(upload_to='asset/'),
        ),
    ]
