# Generated by Django 3.0.8 on 2023-05-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0002_auto_20230522_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncplogs',
            options={'managed': False, 'ordering': ['-pk']},
        ),
    ]
