# Generated by Django 3.0.8 on 2023-05-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0003_auto_20230522_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ncplogs',
            options={'managed': False, 'ordering': ['-eventTime']},
        ),
    ]
