# Generated by Django 3.0.8 on 2023-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0005_auto_20230525_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='NcpLogs',
        ),
    ]
