# Generated by Django 4.1.9 on 2023-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeirenSIEM', '0006_auto_20230529_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100000)),
            ],
        ),
    ]
