# Generated by Django 4.1.9 on 2023-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0008_auto_20230913_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridlayout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
