# Generated by Django 3.0.8 on 2023-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('access_key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(blank=True, max_length=10000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NcpLogs',
            fields=[
                ('hostname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('startTime', models.CharField(blank=True, max_length=10000, null=True)),
                ('startTimeLocal', models.CharField(blank=True, max_length=10000, null=True)),
                ('cmdLine', models.CharField(blank=True, max_length=10000, null=True)),
                ('pid', models.CharField(max_length=10000)),
                ('buildinfo', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'startup_log',
                'managed': False,
            },
        ),
    ]
