# Generated by Django 3.0.8 on 2023-05-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='Admins',
        ),
        migrations.AlterModelTable(
            name='ncplogs',
            table='NCP',
        ),
    ]
