# Generated by Django 3.0.8 on 2023-09-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeirenSIEM', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridlayout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
